// =========================================================================
// Zenoti connector (booking)
// =========================================================================
// Confirmed, openly-documented API - docs.zenoti.com explicitly describes
// this exact use case ("import bookings from external sources"). This is
// real, built from their actual documented request shape.
//
// `config` expected shape: { apiKey: string, centerId: string }
// (apiKey generated by the business in their Zenoti Admin > Configuration
// > Apps; centerId identifies which Zenoti location/branch to book into).
//
// One real limitation worth knowing: Zenoti's booking API needs a Zenoti
// `service_id` and `guest_id` - Tavzio's services aren't automatically
// the same records as Zenoti's, so whoever sets this up needs to map each
// Tavzio service to its matching Zenoti service_id (stored per-service,
// not built into this adapter's signature - see the TODO below for where
// that mapping would need to live once this goes into real use).
// =========================================================================

async function pushBooking(config, booking) {
  if (!config?.apiKey || !config?.centerId) {
    return { success: false, error: 'Zenoti integration is not fully configured (missing API key or center id)' };
  }

  // TODO: this needs a real Zenoti service_id for the booked service, and
  // a Zenoti guest_id for the customer - neither exists yet in Tavzio's
  // data model. The service-to-Zenoti-service_id mapping should live on
  // the `services` table (e.g. a `zenoti_service_id` column) once a real
  // business actually needs this connector; guest_id would need a
  // find-or-create-guest call to Zenoti first, using the customer's phone.
  if (!booking.zenotiServiceId) {
    return { success: false, error: 'This service has not been mapped to a Zenoti service yet' };
  }

  try {
    const response = await fetch('https://api.zenoti.com/v1/bookings', {
      method: 'POST',
      headers: {
        Authorization: `apikey ${config.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        center_id: config.centerId,
        date: booking.requested_at,
        guests: [
          {
            id: booking.zenotiGuestId, // see TODO above
            items: [{ item: { id: booking.zenotiServiceId } }],
          },
        ],
      }),
    });

    const data = await response.json();
    if (!response.ok) {
      return { success: false, error: data.Message || 'Zenoti rejected the booking' };
    }
    return { success: true, externalOrderId: data.id };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

module.exports = { pushBooking };
